accumulate_grad_batches: 1
batch_size: 16
check_val_every_n_epoch: 1
checkpoint_callback: true
data_class: REDataset
data_dir: ./dataset/ske
flush_logs_every_n_steps: 100
gpus: 0,
litmodel_class: SEQLitModel
logger: true
lr: 5.0e-05
max_epochs: 1
max_seq_length: 128
# set max steps to help play demos
max_time: null
min_epochs: null
min_steps: null
model_class: BertForRelationClassification
model_name_or_path: bert-base-chinese
model_type: bert
move_metrics_to_cpu: fals