accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 16
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_class: REDataset
data_dir: ./da