accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 16
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_class: REDataset
data_dir: ./dataset/ske
default_root_dir: null
deterministic: false
distributed_backend: null
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 0,
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_class: INFERLitModel
load_checkpoint: null
log_ev